server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
#  datasource:
#    password:
#    url: jdbc:postgresql://localhost:5432/customer
#    username:
#    jpa:
#      hibernate:
#        ddl-auto: create-drop
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          format_sql: true
#      show-sql: true


  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SHEMA:User_DB}?createDatabaseIfNotExist=true
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    tomcat:
      test-while-idle: true
      validation-query: 1


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
