server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SHEMA:Department_DB}?createDatabaseIfNotExist=true
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    tomcat:
      test-while-idle: true
      validation-query: 1



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost




